import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { BarrelDistortionWebGL } from "@/components/BarrelDistortionWebGL";

const rajdhani = Rajdhani({
  weight: ["500"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CURVED_MONITOR_CONFIG = {
  enabled: true,
  curvature: 0.1,
} as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 1. Move the gradient classes to the body tag */}
      <body className={`${rajdhani.className} antialiased bg-gradient-to-b from-red-900 via-red-950 to-black`}>
        <BarrelDistortionWebGL
          enabled={CURVED_MONITOR_CONFIG.enabled}
          curvature={CURVED_MONITOR_CONFIG.curvature}
        >
          {children}
        </BarrelDistortionWebGL>
      </body>
    </html>
  );
}