import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { BarrelDistortion } from "@/components/BarrelDistortion";

const rajdhani = Rajdhani({
  weight: ["500"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 🖥️ CURVED MONITOR CONFIGURATION
const CURVED_MONITOR_CONFIG = {
  enabled: true,          // Set to false to disable curve effect
  curvature: 0.15,        // 0-0.5: Starting curvature (adjustable with controls)
} as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} antialiased`}>
        <BarrelDistortion 
          enabled={CURVED_MONITOR_CONFIG.enabled}
          curvature={CURVED_MONITOR_CONFIG.curvature}
        >
          {children}
        </BarrelDistortion>
      </body>
    </html>
  );
}