// app/layout.tsx
import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
// 1. Import the new CurvedWrapper
import { CurvedWrapper } from "@/components/CurvedWrapper";

const rajdhani = Rajdhani({
  weight: ["500"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 🖥️ CURVED MONITOR CONFIGURATION
const CURVED_MONITOR_CONFIG = {
  enabled: true,
  // Adjust this value to control the curve. Try values between 50 and 150.
  curvature: 100,
} as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} antialiased bg-gradient-to-b from-red-900 via-red-950 to-black`}>
        {/* 2. Use the new, simpler wrapper component */}
        <CurvedWrapper
          enabled={CURVED_MONITOR_CONFIG.enabled}
          curvature={CURVED_MONITOR_CONFIG.curvature}
        >
          {children}
        </CurvedWrapper>
      </body>
    </html>
  );
}